# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.1.dev37+gbee34b1.d20230127'
__version_tuple__ = version_tuple = (0, 1, 'dev37', 'gbee34b1.d20230127')
